### ISSUE TITLE
lidarr missing directory

### ISSUE THREAD

**Issue by marvthegrate** [cbodden/media-rollout#1]
System Error in Lidarr '''

Remote download client SABnzbd places downloads in /storage/download/complete/audio but this directory does not appear to exist. Likely missing or incorrect remote path mapping. |  
-- | --

'''

**Comment by cbodden** [comment]
I will look into this and issue a patch within the next couple of hours. I think i completely missed the remote path from looking at the code

**Comment by cbodden** [comment]
ifixed and tested
